### ISSUE TITLE
miri reporting UB with "experimental Stacked Borrow rule"

### ISSUE THREAD

**Issue by muja** [joshua-maros/ouroboros#95]
When trying to run my program with miri, it reports UB, however with the note that "the Stacked Borrows rules it violated are still experimental". This minimal example UBs according to miri:

```rust
use ouroboros::self_referencing;
use rc_zip::{
    prelude::*,
    reader::sync::{EntryReader, SyncArchive},
};

#[self_referencing]
pub struct DocxProcessor {
    file: &'static [u8],
    #[borrows(file)]
    #[covariant]
    arc: SyncArchive<'this, &'static [u8]>,
    #[borrows(arc)]
    #[covariant]
    readers: Vec<xml::EventReader<EntryReader<&'this [u8]>>>,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let f = &include_bytes!("../tests/data/Test.docx")[..];
    let mut doc = DocxProcessor::new(
        f,
        |f| f.read_zip_with_size(f.len() as u64).unwrap(),
        |a| vec![xml::EventReader::new(a.by_name("word/document.xml").unwrap().reader())],
    );
    println!("{:?}", doc.next().map(|x| x as char));
    Ok(())
}

impl DocxProcessor {
    fn next(&mut self) -> Result<char, ()> {
        while let Some(Ok(_)) = self.with_readers_mut(|r| Some(r.last_mut()?.next())) {}
        Err(())
    }
}
```

Cargo.toml:

```toml
[package]
name = "ziptest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ouroboros = "0.17.2"

# necessary, otherwise another field is needed holding the `SyncStoredEntry`
# see https://github.com/fasterthanlime/rc-zip/pull/25
rc-zip = { git = "https://github.com/muja/rc-zip" }

xml-rs = "0.8.16"
```

Initially I wanted to see whether using the following code snippet runs into UB, but never got that far:

```rust
self.with_mut(|this| {
    this.readers.push(xml::reader::EventReader::new(
        this.arc.by_name("word/header1.xml").unwrap().reader(),
    ))
});
```

Is this a valid concern or a false positive?

[Test.docx](https://github.com/joshua-maros/ouroboros/files/12142070/Test.docx) (but any Word document should do I guess)

Output:

<img width="1904" alt="image" src="https://github.com/joshua-maros/ouroboros/assets/3709726/6a73a7fd-ee74-46ab-8fe7-815074810bd8">

E: (after looking more closely, this might not even be related to ouroboros.) and yeah, in fact, removing ouroboros completely exhibits the same UB, the problem is in the `circular` crate
